[package]
name = "password-manager-backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
tokio-postgres = "0.7.2"
tokio = { version = "1", features = ["full"] }
